language: rust
rust:
        - stable
        - beta
        - nightly
matrix:
        allow_failures:
                - rust: stable
                - rust: beta
cache: cargo
script:
        - cargo build --verbose --all
